# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VMADemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VMADemo
  pod 'CryptoSwift', '~> 1.0'
  pod 'SwiftyCrypto', '~> 0.0.1'
  

end
